# steps for actually installing wireguard

- name: instal kernel headers
  apt:
    name: "linux-headers-{{ansible_kernel}}"
    state: present

- name: install wireguard packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - wireguard-dkms
    - wireguard-tools
